### ISSUE TITLE
feat: flag for Jacobian

### ISSUE THREAD

**Issue by matteoettam09** [crunchdao/orthogonal-cli#5]
Some user may not be interested in training, just cross-validating; the cli shall have a flag that avoids the computational burden of handling jacobians if not requested.

**Comment by matteoettam09** [comment]
Nice, let's update the README to close the issue @Caceresenzo.

**Comment by Caceresenzo** [comment]
Duplicated of #6, and merged via #7.

**Comment by Caceresenzo** [comment]
Sorry I didn't read the second comment, doing it now.
